### ISSUE TITLE
setup project

### ISSUE THREAD

**Issue by glasgowunion** [glasgowunion/cake#1]
### Setup Project for Development

Provide a basic project skeleton, 
for a typescript mono repo

### Tasks

 - [x] install nix 
   - nix provides a way to boot strap the env if java is not already installed for gradle 
- [x] install nodejs environment
  - node 14x
  - yarn
- [x] install workspace tools
  - lerna
  - setup packages directory for common 
- [x] install typescript
  - install type script and types
  - install global tsconfig which can be inherited 
- [x] setup build tools
  - install gradle
- [x] setup git
  - add gitignore file
  - setup repo
- [x] setup linting tools
  - use waracles styleguide 
  - install prettier
- [x] comitizen for gh commits
- [x] sonarcloud for code qa
- [x] setup gh actions CI

### Expected outputs

- a repo with a packages folder for shared packages
- gradle should be setup to run a couple of basic tasks
- nix should be setup for those that do not have java in their env
- lerna toolset should be in use
- typescript should be configured at repo root and allow packages to inherit/extend this config
- linting should be consitant throughout
- GH Actions should be setup and in use
