### ISSUE TITLE
Cake API

### ISSUE THREAD

**Issue by glasgowunion** [glasgowunion/cake#5]
### Story

As a web application developer
I want to expose a cake api
So i can interact with the service via a websevice

### Requirements

- [x] the API should be a rest API using standard HTTP verbs

### Soft Requirements

- [ ] the API should have pagination

### Acceptance Tests

- [x] should return an array of cakes
- [x] should return a single cake 
- [x] should create a new cake 
- [x] should delete an existing cake

### Design 

- [x]  api should be a lambda aws gateway api
- [ ] responses should be of type json
- [x] responses should be standard HTTP responses e.g. 200, 404, 500
- [x] resources are pluralised e.g. a collection of cakes `/cakes`
- [ ] api responses are wrapped to allow for metadata as api is developed

```
{
"data": [{}]
}
```

**Comment by glasgowunion** [comment]
### Changes to Spec

- responses were not wrapped - instead they are returned as plain objects
- pagination is not implemented

**Comment by glasgowunion** [comment]
### We are going to implement the lambdas in this issue, ready for deployment
